### ISSUE TITLE
 No module named 'caffe'

### ISSUE THREAD

**Issue by m00n420** [aertist/DeepDreamAnimV2#2]
Hi, in colab in  "This will split the video in frames" section, the code don't work:
_Traceback (most recent call last):
  File "dreamer.py", line 19, in <module>
    import caffe
ModuleNotFoundError: No module named 'caffe'_

**Comment by aertist** [comment]
Yes it depends on  caffe. You need to install the caffe frame work first. [Installation guide](https://caffe.berkeleyvision.org/installation.html)
